on:
  # Trigger analysis when creating a pull request and push
  push:
    branches:
      - main
  pull_request:
      branches: [ main ]
      types: [opened, synchronize, reopened]

name: Code Analysis
jobs:
  sonarcloud:
      runs-on: ubuntu-latest
      steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'yarn install'
        run: yarn install --frozen-lockfile
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
